name: "Unit Test"
on: [ pull_request ]
jobs:
  unit-tests:
    runs-on: macos-11
    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v2
      - name: "Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: "Unit Test"
        run: bundle exec fastlane ios tests
